@startuml Create Digital Asset - Process Overview
title Create Digital Asset - Process Overview

actor Alice


box "UBA Server" #LightPink
participant Rest_API as API
end box

participant Token_Store as TS
participant File_Store as FS
participant Commitment_Service as CS

box "BSV | ETH" #lightCyan
participant "Blockchain"
end box


activate Alice
Alice -> API: Asset Create\n(actor, image, name, description, network) 
activate API
API -> TS: Asset Create\n(file_content, filename, actor, name, description) 
activate TS

TS -> FS: Save File\n(file_content, filename)
note left of FS : Image data is\nstored on disk
activate FS
FS --> TS: success
deactivate FS
TS --> API: asset_id, asset_hash
deactivate TS




API -> CS: Commitment Issue\n(actor, asset_id, name, file_hash, network)
activate CS
CS -> TS: Check Token ID
activate TS
TS --> CS: success
deactivate TS

CS -> Blockchain: Create Ownership Tx
activate Blockchain
Blockchain --> CS: TxID
deactivate Blockchain

note right of CS : Create UBA Packet\nand sign it using\nToken Wallet
CS -> TS: Assign ID to Actor\n(actor, asset_id, CPID)
activate TS
TS --> CS: success
deactivate TS
note right of CS : CPID metadata\nsaved in\nCommitment Store
CS --> API: CPID and Metadata
deactivate CS
API --> Alice: actor, asset_id, Status
deactivate API

...

Alice -> API: Asset Retrieve Market()
activate API
API -> TS: Get All Assigned Tokens()
activate TS
TS -> API: assigned_tokens
deactivate TS
' Loop for each actor
loop for each actor
    ' Loop for each token
    loop for each token
        API -> TS: Get Token Filepath(asset_id, actor)
        activate TS
        TS -> TS: Get Token Filename(asset_id, actor)
        TS -> FS: Get File Path(filename)
        activate FS
        FS --> TS: file_path
        deactivate FS
        TS --> API: file_path, filename
        deactivate TS
    end loop
end loop

API --> Alice: Asset List\n(asset_id, name, description, cpid, image_url)
deactivate API

...


Alice -> API: Asset Retrieve\n(asset_id, actor) 
activate API
API -> TS: Get Token Filepath\n(asset_id, actor) 
activate TS
TS -> FS: Get File Path\n(filename)
activate FS
FS --> TS: file_path
deactivate FS
TS --> API: file_path, filename
note right of API: Stream image \nfrom disk
deactivate TS
API --> Alice: File, filename
deactivate API
deactivate Alice



note bottom
    *"Actor" and "Username" 
    are used interchangeably 
    in code and documentation

    *"UBA" and "CPID" also 
    refer to the same concept
end note

@enduml